export const UPLOAD_URL_ID_NUMBER = 'https://dev-api.keywae.com/drivers/v1/register/driver/uploadIdNumber'
export const UPLOAD_URL_DRIVER_NUMBER = 'https://dev-api.keywae.com/drivers/v1/register/driver/uploadDriverNumber'
export const UPLOAD_URL_VEHICLE_REG = 'https://dev-api.keywae.com/drivers/v1/register/driver/uploadVehicleRegNumber'
export const UPLOAD_URL_BANK = 'https://dev-api.keywae.com/drivers/v1/register/driver/uploadBankAccount'
export const UPLOAD_URL_POLICE_REC = 'https://dev-api.keywae.com/drivers/v1/register/driver/uploadPoliceRecCertificate'